### ISSUE TITLE
Support for Dropbox API v2

### ISSUE THREAD

**Issue by riga** [cern-it-sdc-id/gfal2-dropbox#1]
Hi Alejandro,

I couldn't find the Dropbox plugin at https://gitlab.cern.ch/groups/dmc, so I post the issue/suggestion here. A few days ago, the new dropbox API v2 was finally released.
https://blogs.dropbox.com/developers/2015/11/dropbox-api-v2-launches-today/

I think there's not that much to do in order to adapt the changes.

Besides, I cannot get the gfal python bindings working for the dropbox plugin. I use

``` python
ctx.set_opt_string("DROPBOX", "APP_KEY", str(appKey))
ctx.set_opt_string("DROPBOX", "APP_SECRET", str(appSecret))
ctx.set_opt_string("DROPBOX", "ACCESS_TOKEN", str(accessToken))
# no more access token secrets in oauth2
#ctx.set_opt_string("DROPBOX", "ACCESS_TOKEN_SECRET", str(accessTokenSecret))
```

to add the auth data to the transfer parameters. When creating an "App" in Dropbox, it automatically uses oauth2 authentication which hasn't _ACCESS_TOKEN_SECRET_'s anymore (https://www.dropbox.com/developers-v1/core/docs), which leads to errors thrown by https://github.com/cern-it-sdc-id/gfal2-dropbox/blob/c8f7dc418e401e9cc3c0715575e266751081e6cd/src/gfal_dropbox_oauth.c#L45

Could you provide a minimal example showing the dropbox plugin usage in python? I'd really appreciate that =)

**Comment by ayllon** [comment]
Hi,

This plugin does not support oauth2, because we didn't really have the need for FTS3 (WebFTS only supports oauth1).

I'll check how hard could it be to add oauth2 support to the plugin while keeping oauth1 support as well.

I'll also check on the differences between v1 and v2 API's, but that has less priority. Thanks for letting me know, though.

**Comment by ayllon** [comment]
Well, that was easier than expected. Can you please give it a try? Try as

``` python
ctx.set_opt_integer("DROPBOX", "OAUTH", 2)
ctx.set_opt_string("DROPBOX", "APP_KEY", str(appKey))
ctx.set_opt_string("DROPBOX", "APP_SECRET", str(appSecret))
ctx.set_opt_string("DROPBOX", "ACCESS_TOKEN", str(accessToken))

print ctx.listdir("dropbox://www.dropbox.com/")
```

**Comment by riga** [comment]
Works perfectly! Thanks!

Support  for API v1 will be discontinued in the course of 2016 [I guess](https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/), so it's really low priority. Maybe I can contribute a PR for v2.

**Comment by ayllon** [comment]
A PR would be very much appreciated if you get time to work on this before us :smile:

**Comment by riga** [comment]
So, it has been a while ... ;)

Since the V1 API will be turned off in 4 days, I had a look at the [v2 migration guide](https://www.dropbox.com/developers/reference/migration-guide). I think the biggest change to this plugin will result from the fact that all endpoints expect json bodies. Example:

**v1**
```
curl -X GET https://api.dropboxapi.com/1/metadata/auto/Projects?list=false \
--header "Authorization: Bearer <user token>"
```

**v2**
```
curl -X POST https://api.dropboxapi.com/2/files/get_metadata \
--header "Authorization: Bearer <user token>" \
--header "Content-Type: application/json" \
--data "{\"path\": \"/Projects\"}"
```

Therefore, requested paths cannot be passed in the url anymore via `gfal2_dropbox_build_url` (e.g. [here](https://github.com/cern-it-sdc-id/gfal2-dropbox/blob/62b63eb9cbbd76c1f39f92bb89a2d8a5b45f120b/src/gfal_dropbox_ns.c#L33)) but have to be encoded in the request body.

Maybe instead of using the `va_args` in `gfal2_dropbox_build_url` or `gfal2_dropbox_concat_args` which update the url, one could use the same approach to build a json  body using the `va_args`. Do you have a suggestion on how this could be implemented in the current code structure in a clean way? I didn't have the time so far to overlook all places where changes are required ...

Update: Looks like API v1 will be available for another 3 months: https://blogs.dropbox.com/developers/2017/06/updated-api-v1-deprecation-timeline/

**Comment by ayllon** [comment]
Hi,

Sorry for the late reply. I am working on this on a new branch called [v2](https://github.com/cern-it-sdc-id/gfal2-dropbox/tree/v2)

**Comment by riga** [comment]
This is great news! Thanks =)

**Comment by ayllon** [comment]
The branch v2 is ready. Can you give it a try before I merge?

**Comment by riga** [comment]
Ok, I successfully tested

- `stat`
- `unlink`
- `rmdir`
- `mkdir`
- `mkdir_rec`
- `listdir`
- `filecopy`

Works like a charm!
